services:
  - type: web
    name: mgmwa
    env: node
    plan: free
    buildCommand: npm install --legacy-peer-deps
    startCommand: npm start
    autoDeploy: true

    envVars:
      - key: NODE_VERSION
        value: 18

      # ⚙️ PUPPETEER harus download Chrome bawaan sendiri
      - key: PUPPETEER_SKIP_DOWNLOAD
        value: "false"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: ""

      - key: PORT
        value: 10000
      - key: TZ
        value: Asia/Makassar
      - key: KEEPALIVE_URL
        value: https://mgmwa.onrender.com

    healthCheckPath: /
    healthCheckTimeoutSeconds: 60
