services:
  - type: web
    name: mgmwa
    env: node
    plan: free
    buildCommand: |
      echo "⚙️ Installing dependencies..."
      npm install --legacy-peer-deps
      echo "⬇️ Downloading Chromium for Puppeteer..."
      npx puppeteer browsers install chrome
    startCommand: npm start
    autoDeploy: true

    envVars:
      - key: NODE_VERSION
        value: 18

      - key: PUPPETEER_SKIP_DOWNLOAD
        value: "false"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: ""

      - key: PORT
        value: 10000
      - key: TZ
        value: Asia/Makassar
      - key: KEEPALIVE_URL
        value: https://mgmwa.onrender.com

    healthCheckPath: /
    healthCheckTimeoutSeconds: 90
