services:
  - type: web
    name: mgmwa
    env: node
    plan: free
    buildCommand: |
      echo "🏗️ Installing dependencies..."
      npm install
      echo "⬇️ Installing Chromium for Puppeteer..."
      npx puppeteer browsers install chrome
    startCommand: npm start
    autoDeploy: true

    envVars:
      - key: NODE_VERSION
        value: 18
      - key: TZ
        value: Asia/Makassar
      - key: PUPPETEER_SKIP_DOWNLOAD
        value: "true"
      - key: KEEPALIVE_URL
        value: https://mgmwa.onrender.com

    healthCheckPath: /
