services:
  - type: web
    name: mgmwa
    env: node
    plan: free
    buildCommand: |
      echo "⚙️ Installing dependencies..."
      npm install --legacy-peer-deps
      echo "⬇️ Forcing Puppeteer to download Chromium..."
      node node_modules/puppeteer/install.js
    startCommand: npm start
    autoDeploy: true

    envVars:
      - key: NODE_VERSION
        value: 18

      # 🧩 Jangan skip download
      - key: PUPPETEER_SKIP_DOWNLOAD
        value: "false"

      # 🧭 Kosongkan supaya Puppeteer pakai versi internalnya
      - key: PUPPETEER_EXECUTABLE_PATH
        value: ""

      - key: PORT
        value: 10000
      - key: TZ
        value: Asia/Makassar
      - key: KEEPALIVE_URL
        value: https://mgmwa.onrender.com

    healthCheckPath: /
    healthCheckTimeoutSeconds: 90
